### ISSUE TITLE
【优先】quote 信息页选择 Other position，无需填写内容

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1260]
https://dev.classcipe.com/v2/quote

![Image](https://user-images.githubusercontent.com/1272280/208323639-1735f64d-68a7-4db3-8229-1589f1dc85e4.png)

![Image](https://user-images.githubusercontent.com/115767218/198488987-61ccc23e-fc98-469b-ac81-7678b85fd2a0.png)

**Comment by 1547481339** [comment]
前端看一下没保存的字段名是什么
