### ISSUE TITLE
【新】根据用户的状态判断站内信是否可跳转

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1470]
为实现历史上站内信，用户再次点击时，需要判断能否打开站内信的相关页面，在非正常用户或没有协同权限的用户需要跳出无法进入页面的提示图文。

提示框样式参考

协同文件被取消，提示页面
![Image](https://user-images.githubusercontent.com/115767218/202928235-70b08cf1-b2a3-4ce2-9a83-5a780c557564.png)

管理员身份被取消，或老师被学校归档，提示页面
![Image](https://user-images.githubusercontent.com/115767218/202928241-6aef6aae-3f65-4989-bcdc-aaa8b23c3273.png)

管理员身份被取消
场景1: 
-通过classcipe后台添加新的管理员，发送的站内信的情景下，需要判断用户是正常用户或非正常用户（非正常用户为被Delete了的用户）
@1547481339 

![Image](https://user-images.githubusercontent.com/115767218/202605848-7a0f3b46-30f0-43af-b98f-2ec1b64d68fe.png)

场景2:
-通过学校已有的管理员添加新的管理员，发送的站内信的情景下，需要判断用户是正常用户或非正常用户（非正常用户为在学校account 下role manage 页面被Delete了的用户）
@1547481339 

![Image](https://user-images.githubusercontent.com/115767218/202605876-8ff89547-6da7-465c-9d07-09daf33e64fb.png)

老师在学校内归档：
-在学校端添加老师时，发送的站内信的情景下，需要判断用户是正常用户或非正常用户（非正常用户为在老师列表archive 分类下的老师）
@1547481339 

![Image](https://user-images.githubusercontent.com/115767218/202606769-aaf16869-5dc7-4bed-a89a-1bca9c0f32be.png)

-协同编辑时，发送协同邀请站内信，需要判断用户是否有协同权限（被原邀请者删除了协同权限或被邀请者本人删除了协同权限）
@abans 
  ![Image](https://user-images.githubusercontent.com/115767218/200748796-1c458655-4ac2-455a-a5ca-c457e5efb477.png)

后端：以上四种场景后端需要给出老师是否为正常状态判断 / 是否有编辑权限
前端：根据站内信站内跳转的地址来判断协同邀请站内信和学校管理员或学校老师邀请的站内信

**Comment by abans** [comment]
根据id 查询协同状态， 返回 boolean
await App.service('content').get('oldCheckCollaboration', { query: { id: 'content.id' }})

**Comment by 1547481339** [comment]
管理员身份是否有效接口： /classcipe/api2/school/user/isSchoolAdmin  返回true表示该用户是该学校有效的管理员（排除掉delete的）
老师身份是否有效的接口：/classcipe/api2/school/user/isSchoolTeacher  返回true表示该用户是该学校的老师（排除掉reject和archive的）

**Comment by McSam94** [comment]
![Screenshot 2022-11-28 at 9 58 16 AM](https://user-images.githubusercontent.com/39615910/204175609-3769e582-67d5-41cc-8351-aaa16b639386.png)

还是没schoolId
