### ISSUE TITLE
【老】管理后台，学校详情页面 增加save 按钮 与 学校信息 保存一致

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1475]
![Image](https://user-images.githubusercontent.com/115767218/202656790-ecb14b86-44ec-43f4-87e8-4664236bb8c7.png)

**Comment by abans** [comment]
学校内容局部更新接口，更新什么传什么，不需要全传
App.service('school').patch(id, { name: '', country: '', city: '', logo: '', phone_country_code: '', phone_num: '' })
