### ISSUE TITLE
沃森提供个人头像接口，确保个人头像更改后，同步更新

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1495]
![Image](https://user-images.githubusercontent.com/115767218/203457404-48f1d7d9-b5d5-4c3b-bf5c-03ce063b49ad.png)

**Comment by abans** [comment]
https://dev.classcipe.com/doc/#/fio/apis?id=%e4%b8%aa%e4%ba%ba%e8%ba%ab%e4%bb%bd%e7%94%a8%e6%88%b7%e4%bf%a1%e6%81%af%e4%bf%ae%e6%94%b9-new
