### ISSUE TITLE
classcipe后台管理员端无法进一步添加管理员，需要文字提示： You have reached the upper limit of the teachers.

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1502]
目前存在问题1：

根据套餐限制，如果学校老师人数达到了上限，需要确保在classcipe后台管理员端无法进一步添加管理员，需要文字提示： You have reached the upper limit of the teachers.  （目前未解决）

![Image](https://user-images.githubusercontent.com/115767218/204398451-9ba4d868-9ddc-4e31-b4dd-1290545188f0.png)

**Comment by 1547481339** [comment]
学校身份下班级数量不限制，这是之前特意提的需求，请确认是不是又要改

**Comment by 1547481339** [comment]
学生数量和老师数量限制逻辑已处理

**Comment by 1547481339** [comment]
前端也需要控制

**Comment by classcipetest** [comment]
@1547481339 班级那个在学校身份下还是数量不限制，忽略需求，前端会做个优化取消套餐显示。另外有两个新增问题

**Comment by 1547481339** [comment]
套餐里没有设置管理员人数

**Comment by 1547481339** [comment]
学生人数限制问题已处理，需要重新登录

**Comment by 1547481339** [comment]
套餐里没有设置管理员人数，请先把需求对齐
