### ISSUE TITLE
【优先】task session在日历的问题汇总

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1550]
1.日志封面没有读取
2.点击preview 进入404 页面 （https://dev.classcipe.com/v2/session/639652d6667044ec3513eb7c）
3.点击start session now 没有跳转到课堂 

![Image](https://user-images.githubusercontent.com/115767218/206931149-29506689-8091-46a9-8826-fa2fe684fd21.png)

**Comment by eongoo** [comment]
fixed
