### ISSUE TITLE
日历问题-封面图没有读取

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1578]
链接：https://dev.classcipe.com/v2/com/contentSelect/4?start=2022-12-15T11:15:00.000Z&end=2022-12-15T11:30:00.000Z

编辑表单封面图
![Image](https://user-images.githubusercontent.com/115767218/207712881-4429174b-83d9-432d-8777-c22f0c6703bb.png)

日志封面图
![Image](https://user-images.githubusercontent.com/115767218/207713378-465d45da-0bb0-4951-9131-2f44be5687ab.png)

**Comment by eongoo** [comment]
fixed
