### ISSUE TITLE
日历问题- Task session日志拖动，删除，点击预览需求

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1580]
-task session在没有开始的情况，即日志没有置灰，是允许被拖动的 （PD session日志不能被拖动更改）
-拖动日历日志会更改session时间和日期，session列表和session课件preview 页面scheduled的信息需要同步
-未开始的task session 日志允许被删除，一旦删除对应的session 在相应的session列表里消失
删除时跳出确认框
文字： Confirm delete 
Please confirm that you want to delete this item.

          CANCEL YES 

-所有日志可以点击查看缩略图和预览，鼠标放到日志上有“手指”效果，且日志高亮表示可以被选中

![Image](https://user-images.githubusercontent.com/115767218/207719031-3b35ed64-73a9-4b9d-aa5d-8da7ebf55c35.png)

![Image](https://user-images.githubusercontent.com/115767218/207724554-14286046-1709-44fb-900e-978e81b13612.png)

![Image](https://user-images.githubusercontent.com/115767218/207724879-ef9dc26d-9eaf-4cd5-aae2-b7c746b4ffe4.png)

![Image](https://user-images.githubusercontent.com/115767218/207728638-bcaac791-2fc8-48ee-9762-a0aff8af203b.png)

**Comment by eongoo** [comment]
提及的跟日历页面相关的问题修改好了
