### ISSUE TITLE
【优先】日历-按钮需要悬浮

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1585]
![Image](https://user-images.githubusercontent.com/115767218/207773293-8c30dcf4-ecd0-40ad-9842-03dee0825288.png)

![Image](https://user-images.githubusercontent.com/115767218/207773516-3f5fe20d-4672-4e1b-9114-a72b95565120.png)

**Comment by eongoo** [comment]
已经启用新版，Edit 按钮悬浮 问题没有了
