### ISSUE TITLE
Task 编辑页面的后退按钮

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1649]
![Image](https://user-images.githubusercontent.com/115767218/208521988-3a8c8933-6e72-4629-9ab5-2c1edcda15de.png)

![Image](https://user-images.githubusercontent.com/115767218/208522021-ebdc8ec1-ad7f-4e3c-9d3e-5c8721291269.png)

![Image](https://user-images.githubusercontent.com/115767218/208522076-a96bf6c2-71f8-423c-b751-b1aadf6473af.png)

**Comment by abans** [comment]
这是弹窗，不需要后退
