### ISSUE TITLE
首次注册用户进入插件的时候会被谷歌浏览器拦截，需要点击解除拦截才可以重新添加插件。

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1652]
![Image](https://user-images.githubusercontent.com/115767218/208561948-042d74d8-2135-4dcb-be93-1adbb4ae7a83.png)

![Image](https://user-images.githubusercontent.com/115767218/208562583-d68a0100-c4fe-4d92-9196-ee3b162c3563.png)

**Comment by abans** [comment]
没法控制
