### ISSUE TITLE
task/PD 在 schedule session 时，页面跳转逻辑 【优先】

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1658]
1.点击start session now 直接跳进课堂，同时确保schedule 的session 在on-going 分类下呈现 （正确）
2.点击finish按钮，确保不直接跳课堂，而是进入session列表Scheduled 分类下 （目前错误的跳转到了课堂）

![Image](https://user-images.githubusercontent.com/115767218/208790346-813ad494-e1c7-4742-9dcd-b976674866d7.png)

**Comment by eongoo** [comment]
fixed
