### ISSUE TITLE
画板问题汇总

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1659]
![Image](https://user-images.githubusercontent.com/115767218/208790700-8991c20c-6c1f-4b1f-a11a-67a52a973a00.png)
![Image](https://user-images.githubusercontent.com/115767218/208790701-ea3a3745-269e-4671-9b54-550eb2812130.png)
![Image](https://user-images.githubusercontent.com/115767218/208790702-5ee9dcf9-b294-48ae-b421-70e87f93ac46.png)
![Image](https://user-images.githubusercontent.com/115767218/208790703-e6b1b768-4ff2-43bd-b9c9-2c5a3148078d.png)

**Comment by eongoo** [comment]
fixed
