### ISSUE TITLE
课堂-选择题统计图呈现 （问题2-4尚未更改）

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1686]
1.右侧头像选中某个或多个学生时，这些学生对应答案需要在对应的柱状图上高亮呈现或/ 选中某些学生头像时，学生答案未对应的柱状图消失。在统计模式下学生头像默认为全选。（目前的头像的选择没有任何数据反应）
![Image](https://user-images.githubusercontent.com/115767218/209319827-e9b6dd95-0663-4f1b-bab2-3cb3e69642b9.png)

2.鼠标移到柱状图，呈现该答案下的学生名单

3.鼠标移到字母A,B,C上，气泡呈现答案

4.当正确答案开关打开时 ABC 旁边出现对错的判断（打勾或打叉）, Projector 和 Dash同步呈现对错

![Image](https://user-images.githubusercontent.com/115767218/209319721-053c89c9-4884-4acb-b4b0-9be7cf4d50aa.png)

竞品参考

![Image](https://user-images.githubusercontent.com/115767218/209319772-632ea3ed-ead6-4305-986d-287e6d2d355f.png)

**Comment by eongoo** [comment]
fixed
