### ISSUE TITLE
课堂 - projector 和 dash的点击答案同步，滚动无需同步

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1690]
https://user-images.githubusercontent.com/1272280/209486560-583dea1f-5b12-4fa0-8adf-2762b6ea9c04.webm

![Image](https://user-images.githubusercontent.com/115767218/209323526-f6862cc2-fb20-4f5c-bc07-9402d8b03098.png)

**Comment by eongoo** [comment]
滚动也同步了
