### ISSUE TITLE
课堂-画板问题

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1710]
1. 取消整体拖动功能，允许单个拖动

![Image](https://user-images.githubusercontent.com/115767218/209655904-dd1f18f9-b210-4b18-95ae-02cd95500855.png)

2. 编辑框做窄，鼠标移动上去才会变宽

![Image](https://user-images.githubusercontent.com/115767218/209656033-b991be1f-899b-45a0-8f2c-b8e579b6e4ea.png)

**Comment by eongoo** [comment]
fixed

**Comment by eongoo** [comment]
fixed
