### ISSUE TITLE
quick session 问题

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1723]
1.点击PPT有报错
https://dev.frontend.classcipe.com/d/C12yMast?

![Image](https://user-images.githubusercontent.com/115767218/210008843-f9a15121-da5e-4c12-8d9f-33d79743fc6f.png)

https://dev.frontend.classcipe.com/d/C12zVHNY?

2.有的PPT没有题目类型

![Image](https://user-images.githubusercontent.com/115767218/210009164-d6a8b64a-b5c4-4d01-af3d-f37fa9a8393f.png)

**Comment by abans** [comment]
数据问题
