### ISSUE TITLE
teacher paced 和 student paced 切换时，答案呈现样式不统一的问题

### ISSUE THREAD

**Issue by classcipetest** [zran-nz/bug#1727]
teacher- paced时答案呈现样式是统一的，这时dash端打开student-paced且切换另一种答案呈现样式（dash下两端是不同步的，逻辑正确），但是再关闭student-paced回到teacher-paced 后，答案呈现样式在两端需要同步（目前没有实现）

![Image](https://user-images.githubusercontent.com/115767218/209733118-4770f40c-cd80-41d4-9df6-4f045b425fa1.png)

**Comment by abans** [comment]
改为新的状态同步方法
