### ISSUE TITLE
复用task和PD content时PPT的复制逻辑

### ISSUE THREAD

**Issue by KarenWang0813** [zran-nz/bug#209]
A.复用他人含PPT的课件（从Classcipe library / 学校library ）

1. 完成购买
2. 复制快照，出现在my content内（跳转my content页面）
3. 未来某一天，用户进入该内容，点击edit Google slides，进行授权，等待页面，后台下载PPT原件到用户的drive空间
4. 如果用户没有点击edit google slides（未生成PPT）的情况下该内容不能publish（点击publish时打开该内容-显示有未完成的步骤-出现红色叹号，需要补充PPT后，才能发布），但是用户可以schedule（因为改内容已经有了快照）

B.从Edit slides页面选择了library内其他人的内容（训武把library入口恢复吧）

1.支付后，该内容被保存至用户的classcipe drive里，同时出现在my content内，同时直接将复件的快照添加到购物车中（可左右滑动浏览）；
2.点击Edit google slides时读取classcipe drive内容（未授权需要授权，如果用户有若干个google账号，需要选择某个账号）；
3.如果用户没有点击save&go to classcipe,返回my content时，该内容列表出现蒙层，上面save changes按钮（并提醒: The slides in 谷歌账号名称 has not been saved since its last change)，点击生成PPT（如果未授权需要授权）

C. 把用户所有身份下的my content内容合并（贵平），取消create new下面的import按钮（训武）；

D. schedule按钮逻辑：因为所排的课程系统需要获取PPT原件，保存在resource center或featured直播课里，所以如果没有权限则需要先授权，确保系统有权限获得PPT后才能继续排课（贵平&训武）。

E.一份快照同时出现在library和resource center里面，只保留一份原件。
特殊情况：
a.老师先在个人身份下发布了某内容到library并定价，然后又在学校身份下排课被加入学校resource center，学校作为pilot school把内容授权classcipe发布在library里，则该内容只在library出现一次，作者显示老师和老师定价；
b.老师在学校身份下用某个内容排课，学校作为pilot school把内容授权发布在library里，老师再以个人身份发布该内容，则该内容在library内只显示为学校发布的统一定价资源（作者显示学校名称）。

**Comment by nangegpzhang** [comment]
pilot school目前是怎么设置的
