### ISSUE TITLE
沃森验收-推广的注册/登录逻辑

### ISSUE THREAD

**Issue by abans** [zran-nz/bug#260]
登录接口需要增加支持
  - 推广id（string, 记录下来，用来统计推广统计）
 
接口部分：
- 注册回调
  - `curl -H "Content-Type: application/json" -H "Authorization: {token}" /fio/promotes/addCount?_id={_id}&type=signup`
- 登录回调
  - `curl -H "Content-Type: application/json" -H "Authorization: {token}" /fio/promotes/addCount?_id={_id}&type=login`

![Image](https://user-images.githubusercontent.com/1272280/181205904-8fe917cb-1853-4854-ac42-9052262705c1.png)

**Comment by 1547481339** [comment]
已修改
