### ISSUE TITLE
Karen验收-不同format配置下复用内容的显示样式

### ISSUE THREAD

**Issue by KarenWang0813** [zran-nz/bug#282]
Hint显示在文字框里面，灰色斜体

标题名称鼠标点击小叹号时显示：default的名称

复用时section都显示，如果他人的内容（包括他人的自定义）section不存在于自己的模板上，该section显示在最下方
1.背景色区别于正常section，整个多于的区域带虚线的外框；
2.每个section后有删除按钮，可以逐条删除；

![Image](https://user-images.githubusercontent.com/105265752/181655445-70d9d6de-4a83-492c-aacd-c7a53027c962.png)

**Comment by xnuwu** [comment]
不支持放在页面最下面，只能做到加边框，支持删除。

![Image](https://user-images.githubusercontent.com/19685148/182018997-492a6eb0-d2bb-4b3b-ad87-4e712b000498.png)

**Comment by xnuwu** [comment]
unit 支持字段如下


![Image](https://user-images.githubusercontent.com/19685148/182019362-9d3a8306-aa68-4da5-800e-70c0518e98f6.png)



![Image](https://user-images.githubusercontent.com/19685148/182019550-24ab1692-d8e2-49c2-b1b6-bf7a9fe08693.png)



![Image](https://user-images.githubusercontent.com/19685148/182019707-3cb5aeba-2378-4b2b-869f-5a8da6333c45.png)



![Image](https://user-images.githubusercontent.com/19685148/182020020-1a59a903-7219-4d91-8403-9687087831fd.png)

**Comment by KarenWang0813** [comment]
task里面的title，task detail，inquiry question

**Comment by KarenWang0813** [comment]
task里面的title，task detail，inquiry question
