### ISSUE TITLE
学科班级排课页面 加上学科班的时间表

### ISSUE THREAD

**Issue by abans** [zran-nz/bug#463]
![Image](https://user-images.githubusercontent.com/1272280/184478021-384016d6-af72-4b1e-910d-a08b578eb33f.png)

**Comment by xnuwu** [comment]
![Image](https://user-images.githubusercontent.com/19685148/184479692-c37509f2-c4ea-491c-ab0a-89ce32d6a148.png)

**Comment by luorixin** [comment]
和bug 439 重复
