### ISSUE TITLE
系统后台-school-批量上传老师无法下载模版

### ISSUE THREAD

**Issue by Xavier0705** [zran-nz/bug#55]
首先点击“下载模版”

![Image](https://user-images.githubusercontent.com/95326298/178186612-09eca86f-97b1-4fe8-9b20-6cdd87a8ecc0.png)

出现登录页面，没有表单下载

![Image](https://user-images.githubusercontent.com/95326298/178186686-44319277-56c8-49c7-9f3b-a4b4765d7366.png)

**Comment by luorixin** [comment]
页面已经取消
